language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2


script: mvn install

before_install:
- ./etc/before.sh

deploy:
  skip_cleanup: true
  provider: script
  script: mvn deploy
  on:
    branch: master